name: Test

on:
  push:
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

jobs:
  tests:
    name: Test

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.1"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        script: ["copy", "rename"]
        include:
          - php-version: "8.0"
            os: windows-latest
            script: "rename"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Test script
        run: php ${{ matrix.script }}.php
