name: Test

on:
  - push
  - pull_request

jobs:
  tests:
    name: Test

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.1"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Test copy
        run: php copy.php

      - name: Test rename
        run:  php rename.php
